### ISSUE TITLE
1. Write Your First Code Using C# [7 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#2]
Begin your journey by learning to write your first code using C#. Develop a strong foundation as you explore the fundamentals and syntax of the language, setting the stage for your programming adventures.

- [x] tonyjustdevs/learning_csharp#9
- [x] tonyjustdevs/learning_csharp#10
- [x] tonyjustdevs/learning_csharp_vs#9
- [x] tonyjustdevs/learning_csharp_vs#10
- [x] tonyjustdevs/learning_csharp_vs#11
- [x] tonyjustdevs/learning_csharp_vs#12
- [x] tonyjustdevs/learning_csharp_vs#13

[Write your first C# code](https://learn.microsoft.com/en-us/training/modules/csharp-write-first/)

**Comment by tonyjustdevs** [comment]
[Done](https://learn.microsoft.com/en-us/users/tonyjustdevs/achievements/eslgl89p)
