### ISSUE TITLE
3. Add Logic to C# Console Applications [8 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#3]
Unlock the power of logic in C# console applications. Learn how to add logic and decision-making capabilities to your code, enabling your applications to make dynamic choices and respond intelligently to different scenarios.

- [ ] tonyjustdevs/learning_csharp#24
- [ ] tonyjustdevs/learning_csharp#25
- [ ] tonyjustdevs/learning_csharp#26
- [ ] tonyjustdevs/learning_csharp#27
- [ ] tonyjustdevs/learning_csharp#28
- [ ] tonyjustdevs/learning_csharp#29
- [ ] tonyjustdevs/learning_csharp#30
- [ ] tonyjustdevs/learning_csharp#31
