### ISSUE TITLE
4. Work with Variable Data in C# Console Applications [8 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#4]
Discover the versatility of variable data in C# console applications. Harness the ability to store and manipulate different types of data, such as numbers and text, as you delve into the essential concepts of variables and data handling.

- [ ] tonyjustdevs/learning_csharp#32
- [ ] tonyjustdevs/learning_csharp#33
- [ ] tonyjustdevs/learning_csharp#34
- [ ] tonyjustdevs/learning_csharp#35
- [ ] tonyjustdevs/learning_csharp#36
- [ ] tonyjustdevs/learning_csharp#37
- [ ] tonyjustdevs/learning_csharp#38
- [ ] tonyjustdevs/learning_csharp#39
