### ISSUE TITLE
5. Create Methods in C# Console Applications [6 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#5]
Take your C# console applications to the next level by mastering the art of creating methods. Learn how to organize and modularize your code, making it more manageable, reusable, and efficient.

- [ ] tonyjustdevs/learning_csharp#40
- [ ] tonyjustdevs/learning_csharp#41
- [ ] tonyjustdevs/learning_csharp#42
- [ ] tonyjustdevs/learning_csharp#43
- [ ] tonyjustdevs/learning_csharp#44
- [ ] tonyjustdevs/learning_csharp#45
