### ISSUE TITLE
6. Debug C# Console Applications [7 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#6]
Sharpen your troubleshooting skills as you dive into the world of debugging C# console applications. Gain the ability to identify and fix issues in your code, ensuring your applications run smoothly and deliver the desired results.

- [ ] tonyjustdevs/learning_csharp#46
- [ ] tonyjustdevs/learning_csharp#47
- [ ] tonyjustdevs/learning_csharp#48
- [ ] tonyjustdevs/learning_csharp#49
- [ ] tonyjustdevs/learning_csharp#50
- [ ] tonyjustdevs/learning_csharp#51
- [ ] tonyjustdevs/learning_csharp#52
