### ISSUE TITLE
2. Create and Run Simple C# Console Applications [8 Tasks]

### ISSUE THREAD

**Issue by tonyjustdevs** [tonyjustdevs/learning_csharp_vs#8]
Master the art of creating and running simple C# console applications. Dive into the world of console-based programming, where you will gain hands-on experience executing your code and seeing it in action.

- [ ] tonyjustdevs/learning_csharp#16
- [ ] tonyjustdevs/learning_csharp#17
- [ ] tonyjustdevs/learning_csharp#18
- [ ] tonyjustdevs/learning_csharp#19
- [ ] tonyjustdevs/learning_csharp#20
- [ ] tonyjustdevs/learning_csharp#21
- [ ] tonyjustdevs/learning_csharp#22
- [ ] tonyjustdevs/learning_csharp#23
